vcom ../vhdl/io_ctrl.vhd
vcom ../vhdl/io_ctrl_rtl.vhd
vcom ../vhdl/io_ctrl_rtl_cfg.vhd
vcom ../vhdl/calc_ctrl.vhd
vcom ../vhdl/calc_ctrl_rtl.vhd
vcom ../vhdl/calc_ctrl_rtl_cfg.vhd
vcom ../vhdl/alu.vhd
vcom ../vhdl/alu_rtl.vhd
vcom ../vhdl/alu_rtl_cfg.vhd
vcom ../vhdl/calculator.vhd
vcom ../vhdl/calculator_struct.vhd
vcom ../vhdl/calculator_struct_cfg.vhd
vcom ../tb/tb_calculator.vhd
vcom ../tb/tb_calculator_sim.vhd
vcom ../tb/tb_calculator_sim_cfg.vhd
